# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Gitlab-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.5', '3.6', '3.7', '3.8']

    steps:
    - name: install requirements
      run: pip install -r ../requirements.txt
    - name: main
      run: |
        echo "Estamos Dentro"
        python ../main.py
    - name: test
      run: |
        echo "If the files are built successfully, test some files with one command:"
        python ../test.py
